### ISSUE TITLE
Guidelines for implementation in ionic/angular contain misunderstanding

### ISSUE THREAD

**Issue by paulisidore** [capacitor-community/photoviewer#54]
**Is your feature request related to a problem? Please describe.**
Need clarification regarding
"Generate a component in components/photoviewer
in the photoviewer.module.ts file"

Indeed, generating a component in ionic/Angular does not produce a module.ts file

**Describe the solution you'd like**
I think that an update of the guide line must be done with the latest versions of the Ionic/Angular framework

**Describe alternatives you've considered**
I haven't alternative since i cannot achieve the guideline

**Additional context**
I try to add the file photoviewer.module.ts file after generate the component , the build is OK but i got error in console after run the project in Android so i think it's not the right way please confirm.

I use Ionic 7
Capacitor 5

main.ebc658e92bf4d51e.js:1 ERROR Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at Ea.noMatchError (main.ebc658e92bf4d51e.js:1:779237)
    at main.ebc658e92bf4d51e.js:1:779532
    at main.ebc658e92bf4d51e.js:1:517821
    at He._error (main.ebc658e92bf4d51e.js:1:517255)
    at He.error (main.ebc658e92bf4d51e.js:1:509440)
    at He._error (main.ebc658e92bf4d51e.js:1:509684)
    at He.error (main.ebc658e92bf4d51e.js:1:509440)
    at He._error (main.ebc658e92bf4d51e.js:1:509684)
    at He.error (main.ebc658e92bf4d51e.js:1:509440)
    at He._error (main.ebc658e92bf4d51e.js:1:509684)
    at Y (polyfills.441dd4ca9dc0674f.js:1:16047)
    at Y (polyfills.441dd4ca9dc0674f.js:1:15597)
    at polyfills.441dd4ca9dc0674f.js:1:16879
    at v.invokeTask (polyfills.441dd4ca9dc0674f.js:1:7250)
    at Object.onInvokeTask (main.ebc658e92bf4d51e.js:1:605789)
    at v.invokeTask (polyfills.441dd4ca9dc0674f.js:1:7171)
    at h.runTask (polyfills.441dd4ca9dc0674f.js:1:2615)
    at T (polyfills.441dd4ca9dc0674f.js:1:9267)
    at g.invokeTask [as invoke] (polyfills.441dd4ca9dc0674f.js:1:8331)
    at Z (polyfills.441dd4ca9dc0674f.js:1:20909)

**Comment by jepiqueau** [comment]
@paulisidore Sorry to have not answer yet. The documentation at the time that angular uses module, now in ionic7 Angular 16 you can select either module or component so it has to be adapted. i am currently writing a tutorial on it
